name: Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: "${{ github.event.pull_request.base.ref }}"
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies - pip
      run: |
        echo ${{ github.base_ref }}
        python -m pip install --upgrade pip
        curl -sSL https://install.python-poetry.org | python3 -

    - name: "Set up Python"
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'poetry'

    - name: "Install dependencies - poetry"
      run: |
        echo ${{ github.base_ref }}
        poetry install --without code-smells

    - name: Unittest
      env:
        POETRY_VIRTUALENVS_CREATE: true
      run: |
        poetry run coverage run -m unittest discover -v -s ./tests -p "*test*.py"
        poetry run coverage report
