name: Update Package

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      changes:
        value: ${{ jobs.packages.outputs.changes }}
        description: "Get changes in some file"


jobs:
  packages:
    outputs:
      changes: ${{ steps.changes.outputs.changes_detected }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update Lock
      id: update
      run: |
        python -m pip install --upgrade pip
        curl -sSL https://install.python-poetry.org | python3 -
        poetry update

    - name: Updating package
      id: changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "build: Updating package"
